[package]
name = "project_euler"
version = "0.1.0"
authors = ["Dinesh A <adepu.dinesh.a@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
docopt = "1"
serde = "1"
serde_derive = "1"